version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: fbreaper-neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - fbreaper-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fbreaper-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fbreaper-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fbreaper-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - fbreaper-network

  backend:
    build: ./backend-java
    container_name: fbreaper-backend
    depends_on:
      - kafka
      - neo4j
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=neo4jpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    networks:
      - fbreaper-network

  scraper:
    build: ./python_scraper
    container_name: fbreaper-scraper
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_SCRAPE_TOPIC=fbreaper-topic
      - KAFKA_COMMANDS_TOPIC=scraper-control
      - LIBRETRANSLATE_URL=http://libretranslate:5001/translate
    networks:
      - fbreaper-network

  frontend:
    build: ./frontend
    container_name: fbreaper-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - fbreaper-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  kafka_data:

networks:
  fbreaper-network:
    driver: bridge